### ISSUE TITLE
Variable not found issue| getInput<T>()

### ISSUE THREAD

**Issue by ephson24** [BehaviorTree/BehaviorTree.CPP#537]
Hi Davide,

I have this very weird issue with my stack. It isn't one I reproduce easily.
This issue I observed is this; in some instances, the **getInput()** method fails to find the variable and returns a variable not found error.
This is my original setup (that was failing at first):
```c++
BT::NodeStatus isLocalised(BT::TreeNode &self)
{
  ROS_INFO("Localisation check ...");
  std::string loc_topic;
  if(auto res = self.getInput<std::string>("topic"))
    loc_topic = res.value();
  else
    throw std::runtime_error(res.error());
  std::cout << "Topic is: " << loc_topic << std::endl;

  double xy_thresh = 0.0;
  if(auto res = self.getInput<double>("xy_threshold"))
    xy_thresh = res.value();
  else
    throw std::runtime_error(res.error());
  std::cout << "XY_thresh is: " << xy_thresh << std::endl;

  double yaw_thresh = 0.0;
  if(auto res = self.getInput<double>("yaw_threshold"))
    yaw_thresh = res.value();
  else
    throw std::runtime_error(res.error());
  std::cout << "Yaw_thresh is: " << yaw_thresh << std::endl;
  return BT::NodeStatus::SUCCESS;
}
``` 
The error didn't make sense since everything looked okay so I commented out the **else
    throw std::runtime_error(res.error());** part of the checks and to my surprise discovered that the variables were being found alright.
   
After compiling my code a gazillion times and restoring everything back to the original code, there were no errors.
Same code, nothing changed and two very different behaviors. **This is the second time** it has happened but unfortunately there is no way for me to reproduce the error explicitly. 

**Do you think this could be an isolated issue (an issue with my compiler)?** It drives me crazy when it happens.
I have g++, gcc and clang installed on my system but currently I am not specifying which one to use explicitly.

**Comment by ephson24** [comment]
It happened again (I'm using clang now)
**Here is the output:**

```c++
Topic is: /amcl_pose
XY_thresh is: 0.8
Yaw_thresh is: 0.4
terminate called after throwing an instance of 'std::runtime_error'
  what():  Variable not found

Thread 1 "agent_node" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6139859 in __GI_abort () at abort.c:79
#2  0x00007ffff6513911 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff651f38c in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff651f3f7 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff651f6a9 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff70c105c in BT::Ast::ExprName::evaluate (this=0xe34ef0, env=...)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/include/behaviortree_cpp/scripting/operators.hpp:75
#7  0x00007ffff70bf420 in BT::<lambda(BT::Ast::Environment&)>::operator()(BT::Ast::Environment &) const (__closure=0xe34f40, env=...)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/script_parser.cpp:36
#8  0x00007ffff70bfd8f in std::_Function_handler<BT::Any(BT::Ast::Environment&), BT::ParseScript(const string&)::<lambda(BT::Ast::Environment&)> >::_M_invoke(const std::_Any_data &, BT::Ast::Environment &) (__functor=..., __args#0=...)
    at /usr/include/c++/9/bits/std_function.h:286
#9  0x00007ffff705651e in std::function<BT::Any (BT::Ast::Environment&)>::operator()(BT::Ast::Environment&) const (this=0xe34e00, __args#0=...)
    at /usr/include/c++/9/bits/std_function.h:688
#10 0x00007ffff70ba731 in BT::TreeNode::checkPreConditions[abi:cxx11]() (
    this=0xe34b70)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/tree_node.cpp:134
#11 0x00007ffff70ba22e in BT::TreeNode::executeTick (this=0xe34b70)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/tree_node.cpp:53
#12 0x00007ffff7133657 in BT::FallbackNode::tick (this=0xe34770)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/controls/fallback_node.cpp:40
#13 0x00007ffff70ba268 in BT::TreeNode::executeTick (this=0xe34770)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/tree_node.cpp:60
#14 0x00007ffff7133657 in BT::FallbackNode::tick (this=0xe34390)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/controls/fallback_node.cpp:40
#15 0x00007ffff70ba268 in BT::TreeNode::executeTick (this=0xe34390)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/tree_node.cpp:60
#16 0x00007ffff7135a93 in BT::ReactiveSequence::tick (this=0xc2eab0)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/controls/reactive_sequence.cpp:25
#17 0x00007ffff70ba268 in BT::TreeNode::executeTick (this=0xc2eab0)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/tree_node.cpp:60
--Type <RET> for more, q to quit, c to continue without paging--
#18 0x00007ffff7136833 in BT::SequenceWithMemory::tick (this=0x7ac990)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/controls/sequence_star_node.cpp:39
#19 0x00007ffff70ba268 in BT::TreeNode::executeTick (this=0x7ac990)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/tree_node.cpp:60
#20 0x00007ffff704e2cf in BT::Tree::tickRoot (this=0x7fffffffba50, 
    opt=BT::Tree::ONCE_UNLESS_WOKEN_UP, sleep_time=...)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/bt_factory.cpp:570
#21 0x00007ffff704df1a in BT::Tree::tickOnce (this=0x7fffffffba50)
    at /home/ephson/mobrob_ws/src/BehaviorTree.CPP/src/bt_factory.cpp:505
#22 0x00000000005a382d in main (argc=1, argv=0x7fffffffc768)
    at /home/ephson/mobrob_ws/src/mobrob/mobrob_agent/src/agent_node.cpp:174
``` 
As you can see, it found the input variables and then threw a runtime error afterwards.

**Comment by ephson24** [comment]
Yep!, I think the issue may have something to do with the depth of the node in the Behavior Tree.
The same code runs without error at depth 3 (assuming SequenceWithMemory is depth 0) but fails at depth 4 when executed as a child of a Fallback(depth 3) node.

Here's a partial simplified version of my Behavior Tree to show what I mean:
```
<SequenceWithMemory>
    <Fallback>
      <Initialise/>
      <Script code=" isDoingWork:=false; hasMissionTask:=false; UserRequest:=&apos;0;0;0;0;0;0;0;0;0&apos; "/>
    </Fallback>
    <ReactiveSequence>
      <NoteActivity />
      <IsValidActivity />
      <IsSomeActivity />
      <Sequence>
        <IsLocalised topic="/amcl_pose"
                   xy_threshold="0.8"
                   yaw_threshold="0.4"/>
        <Fallback>
          <Inverter>
            <IsSomeNodeUp />
          </Inverter>
          <ControlCustomNode />
        </Fallback>
        <Fallback>
          <IsSomeNodeUp />
          <ControlCustomNode />
        </Fallback>
        <Fallback>
          <IsLocalised topic="/amcl_pose"
                       xy_threshold="0.8"
                       yaw_threshold="0.4"/>
          <ForceFailure>
            <SendAlert message="Localisation mismatch!"
                       severity="ERR"
                       type="NAV"
                       _onSuccess="hasMissionTask=false"/>
          </ForceFailure>
        </Fallback>
  .
  .
  .
  .
```

**Comment by ephson24** [comment]
Figured it out. Seem to be an issue with a variable not being instantiated in the **Script** node
